FirstMVCApp/Models/Products/ProductCreateModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirstMVCApp.Models.Products
{
    public class ProductCreateModel
    {
        [Display(Name = "Наименование")]
        [Required(ErrorMessage = "Наименование должно быть заполненным")]
        public string Name { get; set; }

        [Display(Name = "Категория")]
        [Required(ErrorMessage = "Категория должно быть указана")]
        public int CategoryId { get; set; }

        [Display(Name = "Брэнд")]
        public int? BrandId { get; set; }

        [Display(Name = "Цена")]
        [Required(ErrorMessage = "Цена должно быть указана")]
        [Range(0, Double.PositiveInfinity, ErrorMessage = "Цена не может быть отрицательной")]
        public decimal Price { get; set; }
        public SelectList CategoriesSelect { get; set; }
        public SelectList BrandsSelect { get; set; }
    }
}

FirstMVCApp/Models/Products/ProductFilterModel.cs
namespace FirstMVCApp.Models.Products
{
    public class ProductFilterModel
    {
        public string Name { get; set; }
        public int? CategoryId { get; set; }
        public int? BrandId { get; set; }
        public decimal? PriceFrom { get; set; }
        public decimal? PriceTo { get; set; }
    }
}

FirstMVCApp/Models/Products/ProductModel.cs
namespace FirstMVCApp.Models.Products
{
    public class ProductModel
    {
        public static string NoBrand = "NoName";

        public int Id { get; set; }
        public string Name { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public decimal Price { get; set; }
    }
}

FirstMVCApp/Controllers/OrdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using FirstMVCApp.DAL;
using FirstMVCApp.Models.Orders;
using FirstMVCApp.Models.Products;
using FirstMVCApp.Services.Orders.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class OrdController : Controller
    {
        private readonly IOrdService _ordService;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        public OrdController(IOrdService ordService, IUnitOfWorkFactory unitOfWorkFactory)
        {
            if (ordService == null)
                throw new ArgumentNullException(nameof(ordService));

            _ordService = ordService;
            _unitOfWorkFactory = unitOfWorkFactory;
        }
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.Create())
            {
                var ords = unitOfWork.Ords.GetProductsForOrds().ToList();
                    List<OrdModel> ordModels = Mapper.Map<List<OrdModel>>(ords);
                    return View(ordModels);
            }
        }
        [HttpGet]
        public IActionResult CreateOrd(ProductModel prod)
        {
            var model = _ordService.GetOrdCreateModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult CreateOrd(OrdCreateModel model)
        {
            try
            {
                _ordService.CreateOrd(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

FirstMVCApp/Controllers/ProductController.cs
using System;
using FirstMVCApp.Models.Products;
using FirstMVCApp.Services.Products.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class ProductController : Controller
    {
        // DI - dependency injection
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            if(productService == null)
                throw new ArgumentNullException(nameof(productService));

            _productService = productService;
        }

        //action
        [Route("Search/{name?}/{categoryId?}/{brandId?}/{priceFrom?}/{priceTo?}")]
        public IActionResult Index([FromRoute]ProductFilterModel model)
        {
            try
            {
                var models = _productService.SearchProducts(model);

                return View(models);
            }
            catch (ArgumentOutOfRangeException ex)
            {
                ViewBag.BadRequestMessage = ex.Message;
                return View("BadRequest");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        public IActionResult Create()
        {
            var model = _productService.GetProductCreateModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(ProductCreateModel model)
        {
            try
            {
                _productService.CreateProduct(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        // Category Brand Name Price

        [Route("ololo")]
        public string GetString()
        {
            return "OLOLO";
        }
    }
}

FirstMVCApp/Views/Product/Create.cshtml
@model FirstMVCApp.Models.Products.ProductCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect"></select>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="Model.BrandsSelect">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstMVCApp/Views/Product/Index.cshtml
@model List<FirstMVCApp.Models.Products.ProductModel>
@{
    ViewData["Title"] = "Products";
}

<h1>Products</h1>
<a asp-controller="Product" asp-action="Create">Create</a>
<table>
    <tr>
        <th>Категория</th>
        <th>Брэнд</th>
        <th>Наименование</th>
        <th>Цена</th>
    </tr>
    @foreach (var product in Model)
    {
        <tr>
            <td>@product.CategoryName</td>
            <td>@product.BrandName</td>
            <td><a asp-controller="Ord" asp-action="CreateOrd" asp-route-id="@product.Id"> @product.Name</a></td>
            <td>@product.Price</td>
        </tr>
    }
</table>