FirstMVCApp/Models/Brands/BrandCreateModel.cs
using System.ComponentModel.DataAnnotations;

namespace FirstMVCApp.Models.Brands
{
    public class BrandCreateModel
    {
        [Display(Name = "Наименование")]
        [Required(ErrorMessage = "Наименование должно быть заполненным")]
        public string Name { get; set; }
    }
}

FirstMVCApp/Models/Brands/BrandModel.cs
namespace FirstMVCApp.Models.Brands
{
    public class BrandModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

FirstMVCApp/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using FirstMVCApp.DAL;
using FirstMVCApp.Models.Brands;
using FirstMVCApp.Services.Brands.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        public BrandController(IBrandService brandService, IUnitOfWorkFactory unitOfWorkFactory)
        {
            if (brandService == null)
                throw new ArgumentNullException(nameof(brandService));

            _brandService = brandService;
            _unitOfWorkFactory = unitOfWorkFactory;
        }

        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.Create())
            {
                var brands = unitOfWork.Brands.GetAll().ToList();
                List<BrandModel> brandModels = Mapper.Map<List<BrandModel>>(brands);
                return View(brandModels);
            }
        }

        public IActionResult Create()
        {
            var model = _brandService.GetBrandCreateModel();

            return View(model);
        }
        [HttpPost]
        public IActionResult Create(BrandCreateModel model)
        {
            try
            {
                _brandService.CreateBrand(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

FirstMVCApp/Views/Brand/Create.cshtml
@model FirstMVCApp.Models.Brands.BrandCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstMVCApp/Views/Brand/Index.cshtml
@model List<FirstMVCApp.Models.Brands.BrandModel>
@{
    ViewData["Title"] = "Brands";
}

<h1>Brand</h1>
<a asp-controller="Brand" asp-action="Create">Create</a>
<table>
    <tr>
        <th>Наименование</th>
    </tr>
    @foreach (var brand in Model)
    {
        <tr>
            <td>@brand.Name</td>
        </tr>
    }
</table>